#Лабораторная работа №2

###Задание:   Используя правило Хебба научить персептрон Розенблата распознавать буквы своей фамилии.

#####Рекомендации: Чтобы работать с нейронной сетью нужно на ее входы подавать сигналы в виде чисел (0 или 1). В результате чего, изображение буквы вы должны перевести в последовательность сигналов в виде чисел. Это легко сделать, если представить буквы в строковом формате, например:

<ol>
  <li>1 1 1 1 1</li>
  <li>0 0 1 0 0</li>
  <li>0 0 1 0 0</li>
  <li>0 0 1 0 0</li>
  <li>0 0 1 0 0</li>
</ol>

#####Каждая буква представляет собой 25 квадратиков, причем только двух возможных цветов.
#####Белому квадратику соответствует – 0 , черному – 1.


####Используем упрощенную персептрон Розенблата
###Правила:
#####• Первое правило Хебба — Если сигнал персептрона неверен и равен нулю, то необходимо увеличить веса тех входов, на которые была подана единица.
#####• Второе правило Хебба — Если сигнал персептрона неверен и равен единице, то необходимо уменьшить веса тех входов, на которые была подана единица.

#####Формулы:
w = w + η*x_i

Изначально веса пустые и их первый раз обучают при помощи метода train
Фактически, начальное обучение состоит просто в копировании цифр 0 и 1 из списка словаря-алфавита, а далее при помощи метода train корректируются веса

P.S. - это достаточно простой способ показать, как работает нейросеть, другого примера я не придумал

#####P.S. Использовать матрицу 5Х5

Ниже приведем собственный латинский алфавит

In [13]:
import numpy as np
from math import exp
import random as rm


In [14]:
alphabet = {
"A": np.array([
0,0,1,0,0,
0,1,0,1,0,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]),

"B": np.array([
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0
]),

"C": np.array([
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,0,
1,0,0,0,1,
0,1,1,1,0
]),

"D": np.array([
1,1,1,0,0,
1,0,0,1,0,
1,0,0,0,1,
1,0,0,1,0,
1,1,1,0,0
]),

"E": np.array([
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,1,1,1,1
]),

"F": np.array([
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]),

"G": np.array([
0,1,1,1,0,
1,0,0,0,0,
1,0,1,1,1,
1,0,0,0,1,
0,1,1,1,0
]),

"H": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]),

"I": np.array([
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
1,1,1,1,1
]),

"J": np.array([
0,0,1,1,1,
0,0,0,1,0,
0,0,0,1,0,
1,0,0,1,0,
0,1,1,0,0
]),

"K": np.array([
1,0,0,1,0,
1,0,1,0,0,
1,1,0,0,0,
1,0,1,0,0,
1,0,0,1,0
]),

"L": np.array([
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,1,1,1,1
]),

"M": np.array([
1,0,0,0,1,
1,1,0,1,1,
1,0,1,0,1,
1,0,0,0,1,
1,0,0,0,1
]),

"N": np.array([
1,0,0,0,1,
1,1,0,0,1,
1,0,1,0,1,
1,0,0,1,1,
1,0,0,0,1
]),

"O": np.array([
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]),

"P": np.array([
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]),

"Q": np.array([
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
0,1,1,1,1
]),

"R": np.array([
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,1,0,0,
1,0,0,1,0
]),

"S": np.array([
0,1,1,1,1,
1,0,0,0,0,
0,1,1,1,0,
0,0,0,0,1,
1,1,1,1,0
]),

"T": np.array([
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]),

"U": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]),

"V": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0
]),

"W": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
1,1,0,1,1,
1,0,0,0,1
]),

"X": np.array([
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,1,0,1,0,
1,0,0,0,1
]),

"Y": np.array([
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]),

"Z": np.array([
1,1,1,1,1,
0,0,0,1,0,
0,0,1,0,0,
0,1,0,0,0,
1,1,1,1,1
])
}

In [15]:
A = [
0,0,1,0,0,
0,1,0,1,0,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]

B = [
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0
]

C = [
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,0,
1,0,0,0,1,
0,1,1,1,0
]

D = [
1,1,1,0,0,
1,0,0,1,0,
1,0,0,0,1,
1,0,0,1,0,
1,1,1,0,0
]

E = [
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,1,1,1,1
]

F = [
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]

G = [
0,1,1,1,0,
1,0,0,0,0,
1,0,1,1,1,
1,0,0,0,1,
0,1,1,1,0
]

H = [
1,0,0,0,1,
1,0,0,0,1,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]

I = [
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
1,1,1,1,1
],

J = [
0,0,1,1,1,
0,0,0,1,0,
0,0,0,1,0,
1,0,0,1,0,
0,1,1,0,0
]

K = [
1,0,0,1,0,
1,0,1,0,0,
1,1,0,0,0,
1,0,1,0,0,
1,0,0,1,0
]

L = [
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,1,1,1,1
]

M = [
1,0,0,0,1,
1,1,0,1,1,
1,0,1,0,1,
1,0,0,0,1,
1,0,0,0,1
]

N = [
1,0,0,0,1,
1,1,0,0,1,
1,0,1,0,1,
1,0,0,1,1,
1,0,0,0,1
]

O = [
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]

P = [
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]

Q = [
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
0,1,1,1,1
]

R = [
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,1,0,0,
1,0,0,1,0
]

S = [
0,1,1,1,1,
1,0,0,0,0,
0,1,1,1,0,
0,0,0,0,1,
1,1,1,1,0
]

T = [
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]

U = [
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]

V = [
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0
]

W = [
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
1,1,0,1,1,
1,0,0,0,1
]

X = [
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,1,0,1,0,
1,0,0,0,1
]

Y = [
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]

Z = [
1,1,1,1,1,
0,0,0,1,0,
0,0,1,0,0,
0,1,0,0,0,
1,1,1,1,1
]

In [ ]:
# surname =  "ROMANOV"

# neurons = {}
# input_s = 25
# for target_letter in surname:
#     weights = np.zeros(input_s)
#     for letter in surname:
#         x = alphabet[letter]
#         t = 1 if letter == target_letter else 0
#         weights += x * t
#         print(weights)
#     neurons[target_letter] = weights
# print(neurons)

In [ ]:
# from math import exp
# def sigmoid(x):
#     return 1 / (1 + exp(-x))

####Функция зашумления буквы в фамилии

Делается для того, чтобы посмотреть на процессс работы программы и результаты выполнения

In [ ]:
#Проверка для ниже кода

# s1 = ''
# sample = my_func_noise(o, 3)
# for i in range(len(sample)):
#   if i % 5 == 0:
#     s1 += '\n'
#   s1 += str(sample[i])
# print(s1)

# s2 = ''
# for i in range(len(o)):
#   if i % 5 == 0:
#     s2 += '\n'
#   s2 += str(o[i])
# print(s2)

# print(len(sample))
# print(len(o))

In [18]:
# error_dict = dict()

# x - массив чисел в виде буквы, k - количество изменений
def my_func_noise(x, k):
  x_error = x.copy()
  n = len(x)
  # k = rm.randint(3, n)
  count_k = k # Пока испробуем на k = 3
  indices = rm.sample(range(n), count_k)
  for i in indices:
    x_error[i] = 1 - x_error[i]
  return x_error

#letter - буква, n_version - количество версий для искажений
def my_generate_noise(error_dict, letter, x, k, n_version):
  example = []
  for _ in range(n_version):
    example.append(my_func_noise(x, k))
  array_example = np.array(example)
  error_dict[letter] = array_example

#Пример
# my_generate_noise(error_dict, 'O', O, 3, 4)
# my_generate_noise(error_dict,'N', N, 3, 4)
# print(error_dict)

In [ ]:
# matrix = error_dict['o']
# for v_idx in range(matrix.shape[0]):        # по версиям
#     for b_idx in range(matrix.shape[1]):    # по битам
#         bit = matrix[v_idx, b_idx]
#         print(f"Версия {v_idx}, бит {b_idx} = {bit}")

In [ ]:
# error_dict = dict()
# #x - массив конкретной буквы из словаря, k - количество пикселей, которые можно изменить
# def my_func_noise(x, k):
#   x_error = x
#   index = np.random.choice(len(x), size=k, replace=False)
#   x_error[index] = 1 - x_error[index]
#   return x_error

# #letter - буква, n_version - количество версий для искажений
# def my_generate_noise(letter, x, k, n_version):
#   example = []
#   for _ in range(n_version):
#     example.append(my_func_noise(x, k))
#     print(example)
#   error_dict[letter] = example

# my_generate_noise('o', o, k=3, n_version=4)
# print(error_dict['A'])
# print(alphabet['A'])

In [19]:
def sigmoid(x):
  return 1 / 1  + exp(-x)

Новый Персептрон 3

In [20]:
class Perceptron:
  def __init__(self):
    self.weights = np.zeros(25)
    self.threshold = 0

  """
  x_test - это список одной буквы
  """
  def predict(self, x_test):
    S = np.dot(self.weights, x_test)
    return 1 if S >= self.threshold else 0

  """
  x_train - список образцов
  y_train - список меток 0 или 1 для каждого образца
  n - количество полных проходов по выборке
  """
  def train(self, x_train, y_train, n):
    for i in range(n):
      for x, target in zip(x_train, y_train):
        pred = self.predict(x)
        if pred != target:
          if pred == 0 and target == 1:
            self.weights += x
          elif pred == 1 and target == 0:
            self.weights -= x


###Тест
Рассмотрим пример работы перцептрона Розенблатта с методом Хебба

Задание: Используя правило Хебба научить персептрон Розенблата распознавать буквы своей фамилии.

Фамилия ROMANOV - проверим на каждой букве

In [21]:
error_dict = dict()

my_generate_noise(error_dict, 'R', R, k=3, n_version=4)
my_generate_noise(error_dict,'O', R, k=3, n_version=4)
my_generate_noise(error_dict,'M', R, k=3, n_version=4)
my_generate_noise(error_dict,'A', R, k=3, n_version=4)
my_generate_noise(error_dict,'N', R, k=3, n_version=4)
my_generate_noise(error_dict,'V', R, k=3, n_version=4)

In [22]:
my_generate_noise(error_dict,'X', X, k=3, n_version=4)

In [23]:
print(f"Буква {'X'} - {error_dict['X']}")

Буква X - [[1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 1]
 [0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 1]
 [1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 0]
 [1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1]]


In [24]:
print(f"Буква {'R'} - {error_dict['R']}")
print(f"Буква {'O'} - {error_dict['O']}")
print(f"Буква {'M'} - {error_dict['M']}")
print(f"Буква {'A'} - {error_dict['A']}")
print(f"Буква {'N'} - {error_dict['N']}")
print(f"Буква {'V'} - {error_dict['V']}")

Буква R - [[1 1 1 1 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 0 1 0 0 1 0]
 [0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 1 0 1 0 0]
 [1 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1]]
Буква O - [[1 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0]
 [1 1 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0]
 [1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 0 0 1 0]
 [1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0]]
Буква M - [[0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 0 1 1 0]
 [1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0]
 [1 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 0]]
Буква A - [[1 1 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 1 0 0 1 0]
 [0 1 1 1 1 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0]]
Буква N - [[1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0

Здесь сделаем различные выборки для каждой отдельной буквы

In [25]:
# Положительные примеры (класс 1) – оригинал + все искажённые
X_pos = [O] + list(error_dict['O'])   # список из 5 образцов
y_pos = [1] * len(X_pos)                       # [1,1,1,1,1]

# Отрицательные примеры (класс 0) – например, другая буква 'x'
X_neg = [X] + list(error_dict['X'])
y_neg = [0] * len(X_neg)

# Объединяем
X_train = X_pos + X_neg
y_train = y_pos + y_neg

Обучение перцептрона

In [26]:
perceptron = Perceptron()
perceptron.train(X_train, y_train, n=5)

print("Обученные веса:", perceptron.weights)

Обученные веса: [ 0.  1.  1.  1. -1.  1. -1.  0. -1.  0.  1.  1. -1.  1.  0.  1. -1.  1.
 -1.  0.  0.  1.  0.  1. -1.]


Тестирование

In [36]:
# Возьмём новую искажённую версию (не из обучающего набора, например, с другим шумом)
error_dict_test = dict()
my_generate_noise(error_dict_test, 'O', O, k=3, n_version=2)
my_generate_noise(error_dict_test, 'X', X, k=3, n_version=1)
pred = perceptron.predict(error_dict_test['O'][1])
print(f"Тестовый образец (искажённая 'o'): предсказание = {pred} (должно быть 1)")

# Тест на отрицательном примере
pred_x = perceptron.predict(X)
print(f"Буква 'x': предсказание = {pred_x} (должно быть 0)")

Тестовый образец (искажённая 'o'): предсказание = 1 (должно быть 1)
Буква 'x': предсказание = 0 (должно быть 0)


Оценка точности

In [37]:
# Сформируем тестовую выборку (отдельные образцы, не участвовавшие в обучении)
X_test = [error_dict_test['O'][0], error_dict_test['X'][0]]
y_test = [1, 0]

correct = 0
for x, true in zip(X_test, y_test):
    pred = perceptron.predict(x)
    if pred == true:
        correct += 1
print(f"Точность на тесте: {correct / len(X_test) * 100:.1f}%")

Точность на тесте: 100.0%


###Класс персептрона Розенблата 2

#####Суть будет следующим:
На вход будут подаваться буквы моей фамилии, но перед этим они пройдут "шумомизацию", т.е. в некоторых "пикселях" будут зашумления, чтобы посмотреть, как сеть справится с такими сложностями и сможет ли предсказать правильность ответа. - это все фигня

Так как в задании сказано, что мы должны распозновать БУКВУ своей фаимилии, то будем для каждой БУКВЕ создавать новые экземпляры

In [ ]:
class Perceptron:
  def __init__(self):
    self.size = 25 # 25 клеток (нейронов)
    self.nerouns = dict() #Веса
    self.result = dict() #Буквы
    self.predicted = 0

  """
  letter - буква массива (передаем символ)
  x_train - сам массив буквы
  y_train - алфавит
  """
  def train_perceptron(self, letter, x_train, y_train):
    #Изначальная инициализация именно в методе train
    maska = 1
    weight = np.zeros(self.size)

    x_i = y_train[letter]
    weight += x_i * maska
    self.nerouns[letter] = weight

  """
  letter - буква массив (передаем символ)
  x_test - массив списков, которые являются тестами
  y_test - алфавит (формально это одно и тоже как в выше функции)
  """
  def predict_perceptron(self, letter, x_test, y_test):
    # Использование правила Хебба и сигмоидной функции
    """
    Мысли:
    Сначала надо понять, как перебирать элементы из словаря error_dict
    Далее для каждого списка из словаря error_dict обработать по правилу Хебба с исходным список из словаря alphabet
    Далее из всех пискселей суммируем по правилу value*weight, а далее по сигмоиде определяем буква или нет
    И так смотрим по правилу хебба корректируем веса
    """
    matrix = error_dict[letter]
    for v_idx in range(matrix.shape[0]):        # по версиям
        for b_idx in range(matrix.shape[1]):    # по битам
            bit = matrix[v_idx, b_idx]
            print(f"Версия {v_idx}, бит {b_idx} = {bit}")


Персептрон 1


In [ ]:
class Perceptron:
  def __init__(self, size):
    self.size = size
    self.nerouns = dict() #И есть веса
    self.result = dict() #Буквы
    self.predicted = 0
    # threshold = 1

  # x_train - норм символьный текст, y_train - алфавит
  def train(self, x_train, y_train):
    for targer_elem in x_train:
      weights = np.zeros(self.size)
      for elem in x_train:
        x_i = y_train[elem]
        maska = 1 if elem == targer_elem else 0
        weights += x_i * maska
      self.nerouns[targer_elem] = weights

  #x_test - зашумленный текст - это error_dict
  def predict(self, x_test):
    # result = dict()
    for letter, weight in self.nerouns.items():
      print(letter, weight)
      for letter_error in x_test.get(letter):
        print(letter_error)
        S = np.dot(weight, letter_error)
        self.result[letter] = S
    self.predicted = max(self.result, key=self.result.get)



###Пример использования

In [ ]:
surname =  "ROMANOV"

#Сделаем зашумление каждой буквы своей Фамилии
for letter in surname:
  my_generate_noise(letter, alphabet[letter], k=3, n_version=2)

for i in error_dict.items():
  print(i)



('A', [array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0]), array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0])])
('R', [array([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1]), array([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1])])
('O', [array([1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1]), array([1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1])])
('M', [array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0]), array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0])])
('N', [array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0]), array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0])])
('V', [array([0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 

In [ ]:
obj1 = Perceptron(25)

obj1.train(surname, alphabet)

#Видим веса:
print(obj1.nerouns)

{'R': array([1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 1.]), 'O': array([2., 0., 0., 2., 2., 2., 0., 2., 0., 0., 0., 2., 0., 2., 0., 2., 2.,
       2., 2., 2., 2., 2., 2., 0., 2.]), 'M': array([1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 1., 0.]), 'A': array([0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 1., 0.]), 'N': array([1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0.]), 'V': array([0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1.])}


In [ ]:
obj1.predict(error_dict)

R [1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.
 1.]
[1 1 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1]
[1 1 0 0 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1]
O [2. 0. 0. 2. 2. 2. 0. 2. 0. 0. 0. 2. 0. 2. 0. 2. 2. 2. 2. 2. 2. 2. 2. 0.
 2.]
[1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1]
[1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1]
M [1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1.
 0.]
[1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0]
[1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0]
A [0. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1.
 0.]
[0 0 1 0 1 1 1 0 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0]
[0 0 1 0 1 1 1 0 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0]
N [1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1.
 0.]
[1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 1 0]
[1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 1 0]
V [0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1.
 1.]


In [ ]:
print(obj1.result)
print(obj1.predicted)

{'R': np.float64(12.0), 'O': np.float64(32.0), 'M': np.float64(11.0), 'A': np.float64(10.0), 'N': np.float64(15.0), 'V': np.float64(15.0)}
O
