#Лабораторная работа №2

###Задание:   Используя правило Хебба научить персептрон Розенблата распознавать буквы своей фамилии.

#####Рекомендации: Чтобы работать с нейронной сетью нужно на ее входы подавать сигналы в виде чисел (0 или 1). В результате чего, изображение буквы вы должны перевести в последовательность сигналов в виде чисел. Это легко сделать, если представить буквы в строковом формате, например:

<ol>
  <li>1 1 1 1 1</li>
  <li>0 0 1 0 0</li>
  <li>0 0 1 0 0</li>
  <li>0 0 1 0 0</li>
  <li>0 0 1 0 0</li>
</ol>

#####Каждая буква представляет собой 25 квадратиков, причем только двух возможных цветов.
#####Белому квадратику соответствует – 0 , черному – 1.


####Используем упрощенную персептрон Розенблата
###Правила:
#####• Первое правило Хебба — Если сигнал персептрона неверен и равен нулю, то необходимо увеличить веса тех входов, на которые была подана единица.
#####• Второе правило Хебба — Если сигнал персептрона неверен и равен единице, то необходимо уменьшить веса тех входов, на которые была подана единица.

#####Формулы:
w = w + η*x_i

Изначально веса пустые и их первый раз обучают при помощи метода train
Фактически, начальное обучение состоит просто в копировании цифр 0 и 1 из списка словаря-алфавита, а далее при помощи метода train корректируются веса

P.S. - это достаточно простой способ показать, как работает нейросеть, другого примера я не придумал

#####P.S. Использовать матрицу 5Х5

Ниже приведем собственный латинский алфавит

In [13]:
import numpy as np
from math import exp
import random as rm


In [14]:
alphabet = {
"A": np.array([
0,0,1,0,0,
0,1,0,1,0,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]),

"B": np.array([
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0
]),

"C": np.array([
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,0,
1,0,0,0,1,
0,1,1,1,0
]),

"D": np.array([
1,1,1,0,0,
1,0,0,1,0,
1,0,0,0,1,
1,0,0,1,0,
1,1,1,0,0
]),

"E": np.array([
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,1,1,1,1
]),

"F": np.array([
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]),

"G": np.array([
0,1,1,1,0,
1,0,0,0,0,
1,0,1,1,1,
1,0,0,0,1,
0,1,1,1,0
]),

"H": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]),

"I": np.array([
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
1,1,1,1,1
]),

"J": np.array([
0,0,1,1,1,
0,0,0,1,0,
0,0,0,1,0,
1,0,0,1,0,
0,1,1,0,0
]),

"K": np.array([
1,0,0,1,0,
1,0,1,0,0,
1,1,0,0,0,
1,0,1,0,0,
1,0,0,1,0
]),

"L": np.array([
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,1,1,1,1
]),

"M": np.array([
1,0,0,0,1,
1,1,0,1,1,
1,0,1,0,1,
1,0,0,0,1,
1,0,0,0,1
]),

"N": np.array([
1,0,0,0,1,
1,1,0,0,1,
1,0,1,0,1,
1,0,0,1,1,
1,0,0,0,1
]),

"O": np.array([
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]),

"P": np.array([
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]),

"Q": np.array([
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
0,1,1,1,1
]),

"R": np.array([
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,1,0,0,
1,0,0,1,0
]),

"S": np.array([
0,1,1,1,1,
1,0,0,0,0,
0,1,1,1,0,
0,0,0,0,1,
1,1,1,1,0
]),

"T": np.array([
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]),

"U": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]),

"V": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0
]),

"W": np.array([
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
1,1,0,1,1,
1,0,0,0,1
]),

"X": np.array([
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,1,0,1,0,
1,0,0,0,1
]),

"Y": np.array([
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]),

"Z": np.array([
1,1,1,1,1,
0,0,0,1,0,
0,0,1,0,0,
0,1,0,0,0,
1,1,1,1,1
])
}

In [15]:
A = [
0,0,1,0,0,
0,1,0,1,0,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]

B = [
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0
]

C = [
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,0,
1,0,0,0,1,
0,1,1,1,0
]

D = [
1,1,1,0,0,
1,0,0,1,0,
1,0,0,0,1,
1,0,0,1,0,
1,1,1,0,0
]

E = [
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,1,1,1,1
]

F = [
1,1,1,1,1,
1,0,0,0,0,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]

G = [
0,1,1,1,0,
1,0,0,0,0,
1,0,1,1,1,
1,0,0,0,1,
0,1,1,1,0
]

H = [
1,0,0,0,1,
1,0,0,0,1,
1,1,1,1,1,
1,0,0,0,1,
1,0,0,0,1
]

I = [
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
1,1,1,1,1
],

J = [
0,0,1,1,1,
0,0,0,1,0,
0,0,0,1,0,
1,0,0,1,0,
0,1,1,0,0
]

K = [
1,0,0,1,0,
1,0,1,0,0,
1,1,0,0,0,
1,0,1,0,0,
1,0,0,1,0
]

L = [
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,0,0,0,0,
1,1,1,1,1
]

M = [
1,0,0,0,1,
1,1,0,1,1,
1,0,1,0,1,
1,0,0,0,1,
1,0,0,0,1
]

N = [
1,0,0,0,1,
1,1,0,0,1,
1,0,1,0,1,
1,0,0,1,1,
1,0,0,0,1
]

O = [
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]

P = [
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,0,0,0,
1,0,0,0,0
]

Q = [
0,1,1,1,0,
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
0,1,1,1,1
]

R = [
1,1,1,1,0,
1,0,0,0,1,
1,1,1,1,0,
1,0,1,0,0,
1,0,0,1,0
]

S = [
0,1,1,1,1,
1,0,0,0,0,
0,1,1,1,0,
0,0,0,0,1,
1,1,1,1,0
]

T = [
1,1,1,1,1,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]

U = [
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,1,1,0
]

V = [
1,0,0,0,1,
1,0,0,0,1,
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0
]

W = [
1,0,0,0,1,
1,0,0,0,1,
1,0,1,0,1,
1,1,0,1,1,
1,0,0,0,1
]

X = [
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,1,0,1,0,
1,0,0,0,1
]

Y = [
1,0,0,0,1,
0,1,0,1,0,
0,0,1,0,0,
0,0,1,0,0,
0,0,1,0,0
]

Z = [
1,1,1,1,1,
0,0,0,1,0,
0,0,1,0,0,
0,1,0,0,0,
1,1,1,1,1
]

####Функция зашумления буквы в фамилии

Делается для того, чтобы посмотреть на процессс работы программы и результаты выполнения

In [18]:
# error_dict = dict()

# x - массив чисел в виде буквы, k - количество изменений
def my_func_noise(x, k):
  x_error = x.copy()
  n = len(x)
  # k = rm.randint(3, n)
  count_k = k # Пока испробуем на k = 3
  indices = rm.sample(range(n), count_k)
  for i in indices:
    x_error[i] = 1 - x_error[i]
  return x_error

#letter - буква, n_version - количество версий для искажений
def my_generate_noise(error_dict, letter, x, k, n_version):
  example = []
  for _ in range(n_version):
    example.append(my_func_noise(x, k))
  array_example = np.array(example)
  error_dict[letter] = array_example

#Пример
# my_generate_noise(error_dict, 'O', O, 3, 4)
# my_generate_noise(error_dict,'N', N, 3, 4)
# print(error_dict)

In [19]:
def sigmoid(x):
  return 1 / 1  + exp(-x)

Новый Персептрон 3

In [20]:
class Perceptron:
  def __init__(self):
    self.weights = np.zeros(25)
    self.threshold = 0

  """
  x_test - это список одной буквы
  """
  def predict(self, x_test):
    S = np.dot(self.weights, x_test)
    return 1 if S >= self.threshold else 0

  """
  x_train - список образцов
  y_train - список меток 0 или 1 для каждого образца
  n - количество полных проходов по выборке
  """
  def train(self, x_train, y_train, n):
    for i in range(n):
      for x, target in zip(x_train, y_train):
        pred = self.predict(x)
        if pred != target:
          if pred == 0 and target == 1:
            self.weights += x
          elif pred == 1 and target == 0:
            self.weights -= x


###Тест
Рассмотрим пример работы перцептрона Розенблатта с методом Хебба

Задание: Используя правило Хебба научить персептрон Розенблата распознавать буквы своей фамилии.

Фамилия ROMANOV - проверим на каждой букве

In [21]:
error_dict = dict()

my_generate_noise(error_dict, 'R', R, k=3, n_version=4)
my_generate_noise(error_dict,'O', R, k=3, n_version=4)
my_generate_noise(error_dict,'M', R, k=3, n_version=4)
my_generate_noise(error_dict,'A', R, k=3, n_version=4)
my_generate_noise(error_dict,'N', R, k=3, n_version=4)
my_generate_noise(error_dict,'V', R, k=3, n_version=4)

In [22]:
my_generate_noise(error_dict,'X', X, k=3, n_version=4)

In [23]:
print(f"Буква {'X'} - {error_dict['X']}")

Буква X - [[1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 1]
 [0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 0 1 0 1 0 1 0 0 0 1]
 [1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 0]
 [1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1]]


In [24]:
print(f"Буква {'R'} - {error_dict['R']}")
print(f"Буква {'O'} - {error_dict['O']}")
print(f"Буква {'M'} - {error_dict['M']}")
print(f"Буква {'A'} - {error_dict['A']}")
print(f"Буква {'N'} - {error_dict['N']}")
print(f"Буква {'V'} - {error_dict['V']}")

Буква R - [[1 1 1 1 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 0 1 0 0 1 0]
 [0 1 1 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 1 0 1 0 0]
 [1 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1]]
Буква O - [[1 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0]
 [1 1 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 0]
 [1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 0 0 1 0]
 [1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0]]
Буква M - [[0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 0 1 1 0]
 [1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0]
 [1 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 1 1 1 0 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 0]]
Буква A - [[1 1 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 0]
 [1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 0 0 0 0 1 0 0 1 0]
 [0 1 1 1 1 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0]]
Буква N - [[1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0

Здесь сделаем различные выборки для каждой отдельной буквы

In [25]:
# Положительные примеры (класс 1) – оригинал + все искажённые
X_pos = [O] + list(error_dict['O'])   # список из 5 образцов
y_pos = [1] * len(X_pos)                       # [1,1,1,1,1]

# Отрицательные примеры (класс 0) – например, другая буква 'x'
X_neg = [X] + list(error_dict['X'])
y_neg = [0] * len(X_neg)

# Объединяем
X_train = X_pos + X_neg
y_train = y_pos + y_neg

Обучение перцептрона

In [26]:
perceptron = Perceptron()
perceptron.train(X_train, y_train, n=5)

print("Обученные веса:", perceptron.weights)

Обученные веса: [ 0.  1.  1.  1. -1.  1. -1.  0. -1.  0.  1.  1. -1.  1.  0.  1. -1.  1.
 -1.  0.  0.  1.  0.  1. -1.]


Тестирование

In [36]:
# Возьмём новую искажённую версию (не из обучающего набора, например, с другим шумом)
error_dict_test = dict()
my_generate_noise(error_dict_test, 'O', O, k=3, n_version=2)
my_generate_noise(error_dict_test, 'X', X, k=3, n_version=1)
pred = perceptron.predict(error_dict_test['O'][1])
print(f"Тестовый образец (искажённая 'o'): предсказание = {pred} (должно быть 1)")

# Тест на отрицательном примере
pred_x = perceptron.predict(X)
print(f"Буква 'x': предсказание = {pred_x} (должно быть 0)")

Тестовый образец (искажённая 'o'): предсказание = 1 (должно быть 1)
Буква 'x': предсказание = 0 (должно быть 0)


Оценка точности

In [37]:
# Сформируем тестовую выборку (отдельные образцы, не участвовавшие в обучении)
X_test = [error_dict_test['O'][0], error_dict_test['X'][0]]
y_test = [1, 0]

correct = 0
for x, true in zip(X_test, y_test):
    pred = perceptron.predict(x)
    if pred == true:
        correct += 1
print(f"Точность на тесте: {correct / len(X_test) * 100:.1f}%")

Точность на тесте: 100.0%
